### ISSUE TITLE
slc arc error in component module

### ISSUE THREAD

**Issue by casamia918** [strongloop/loopback-example-xamarin#4]
I cloned this repo and tested how the apps are working. While running in local environment with excute "$ node .", no problem at all. 

After that, I tried to deploy this app to cloud server (aws ec2) to test my server setting in production environment. As you know, loopback uses strongloop pm in host to running loopback process and deploy the tar file from local to host using arc build & deploy module . 

When I excute "$ slc arc", it opens arc GUI. But when I click composer module, it shows error message with 'Missing server facet' message. What's the problem, and how fix the problem?
![screen shot 2016-04-18 at 10 17 50 pm](https://cloud.githubusercontent.com/assets/8295005/14605413/6922ac18-05b3-11e6-8b8a-bdf5e0b82321.png)

[version information]
OSX 10.11.3
node v4.4.3
npm 2.15.1
strongloop 6.0.0
loopback 2.27.0

**Comment by richardpringle** [comment]
I believe that this issue is with Arc if it runs fine locally. Could you post in there instead? https://github.com/strongloop/strongloop/issues

**Comment by richardpringle** [comment]
Actually, @casamia918 please see this page: https://strongloop.com/node-js/arc. We are no longer supporting Arc unless you are a paid customer (in which case you should probably contact support directly). 

I encourage checking out [API Connect](https://strongloop.com/node-js/api-connect/) though. It's a pretty big upgrade from arc with more enterprise functionality!

Will close this issue for now, please feel free to re-open if the issue persists with API Connect and mention me directly in the description. 

Cheers
